export const Hola = 'Hello'
export const Hola1 = 'Hello'
export const Hola2 = 'Hello'
export const Hola3 = 'Hello'
export const Hola4 = 'Hello'

export const Todoos = 'Todoos'
export const Todoos1 = 'Todoos'
export const Todoos2 = 'Todoos'
export const Todoos3 = 'Todoos'
export const Todoos4 = 'Todoos'